name: smct
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  google_fonts: ^3.0.1
  equatable: ^2.0.3
  animations: ^2.0.3
  flutter_svg: ^1.1.0
  bloc_concurrency: ^0.2.0
  grpc: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/btn.svg
    - assets/svg/play_btn.svg
    - assets/svg/division.svg
    - assets/svg/subtraction.svg
    - assets/svg/multiplication.svg
    - assets/svg/summation.svg
    - assets/anim/plus.json
    - assets/anim/minus.json
    - assets/anim/div.json